In [1]:
import torch

AttributeError: partially initialized module 'torch' from 'c:\Users\liamr\docker_deployment_demo\env\Lib\site-packages\torch\__init__.py' has no attribute 'Tensor' (most likely due to a circular import)

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.device_count()

1

In [4]:
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 4060 Laptop GPU'

In [5]:
torch.cuda.device(0)

### Tensors

In [6]:
import numpy as np
npArr = np.array([[1,2,3], [1, 2, 3]])

tensor = torch.tensor([[[[1., 2.], 
                            [3., 4.]], [[1., 2.], 
                                        [3., 4.]], [[1., 2.], 
                                                    [3., 4.]]], [[[1., 2.], 
                                                                  [3., 4.]], [[1., 2.], 
                                                                              [3., 4.]], [[1., 2.], 
                                                                                          [3., 4.]]]]) 

print(tensor.size())


torch.Size([2, 3, 2, 2])


In [7]:
tensor.to("cuda")

tensor([[[[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]]],


        [[[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]]]], device='cuda:0')

### Autograd

In [8]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

f = 3 * a**3 - b**2
f

tensor([-12.,  65.], grad_fn=<SubBackward0>)

$$f= 3a^3 -b^2$$
$$\frac{\partial f}{\partial a} = 9a^2$$
$$\frac{\partial f}{\partial b} = -2b$$


In [9]:
f.backward(gradient=torch.tensor([1,1]))
print(a.grad)
print(b.grad)

tensor([36., 81.])
tensor([-12.,  -8.])


### Basic NN

In [10]:
import torch.nn as nn
import torch.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
X, y = load_breast_cancer(return_X_y=True)

X_train, y_train, = train_test_split(x)