In [38]:
import torch

In [39]:
torch.cuda.is_available()

True

In [40]:
torch.cuda.device_count()

1

In [41]:
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 4060 Laptop GPU'

In [42]:
torch.cuda.device(0)

### Tensors

In [43]:
import numpy as np
npArr = np.array([[1,2,3], [1, 2, 3]])

tensor = torch.tensor([[[[1., 2.], 
                            [3., 4.]], [[1., 2.], 
                                        [3., 4.]], [[1., 2.], 
                                                    [3., 4.]]], [[[1., 2.], 
                                                                  [3., 4.]], [[1., 2.], 
                                                                              [3., 4.]], [[1., 2.], 
                                                                                          [3., 4.]]]]) 

print(tensor.size())


torch.Size([2, 3, 2, 2])


In [44]:
tensor.to("cuda")

tensor([[[[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]]],


        [[[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]]]], device='cuda:0')

### Autograd

In [46]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

f = 3 * a**3 - b**2
f

tensor([-12.,  65.], grad_fn=<SubBackward0>)

$$f= 3a^3 -b^2$$
$$\frac{\partial f}{\partial a} = 9a^2$$
$$\frac{\partial f}{\partial b} = -2b$$


In [48]:
f.backward(gradient=torch.tensor([1,1]))
print(a.grad)
print(b.grad)

tensor([36., 81.])
tensor([-12.,  -8.])
