In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.device_count()

1

In [4]:
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 5070 Ti'

In [5]:
torch.cuda.device(0)

### Tensors

In [6]:
import numpy as np
npArr = np.array([[1,2,3], [1, 2, 3]])

tensor = torch.tensor([[[[1., 2.], 
                            [3., 4.]], [[1., 2.], 
                                        [3., 4.]], [[1., 2.], 
                                                    [3., 4.]]], [[[1., 2.], 
                                                                  [3., 4.]], [[1., 2.], 
                                                                              [3., 4.]], [[1., 2.], 
                                                                                          [3., 4.]]]]) 

print(tensor.size())


torch.Size([2, 3, 2, 2])


In [7]:
tensor.to("cuda")

tensor([[[[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]]],


        [[[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]]]], device='cuda:0')

### Autograd

In [8]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

f = 3 * a**3 - b**2
f

tensor([-12.,  65.], grad_fn=<SubBackward0>)

$$f= 3a^3 -b^2$$
$$\frac{\partial f}{\partial a} = 9a^2$$
$$\frac{\partial f}{\partial b} = -2b$$


In [9]:
f.backward(gradient=torch.tensor([1,1]))
print(a.grad)
print(b.grad)

tensor([36., 81.])
tensor([-12.,  -8.])


### Basic NN

In [17]:
import torch.nn as nn
import torch.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [23]:
#set up the data that will train and test the NN
X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2)
scalar = StandardScaler()
X_train_scaled = scalar.fit_transform(X_train)
X_test_scaled = scalar.fit_transform(X_test)

### Turning the data into Tensors

In [ ]:
X_train_scaled_tesnor = torch.from_numpy(X_train_scaled).float()
X_test_scaled_tesnor = torch.from_numpy(X_test_scaled).float()
y_train_tensor = torch.from_numpy(y_train).float().unsqueeze(1)   #turns this from a 1d array to a 2d array
y_test_tensor = torch.from_numpy(y_test).float().unsqueeze(1)     #because pytoarch needs 2d arrays?

In [25]:
train_dataset = TensorDataset(X_train_scaled_tesnor, y_train_tensor)

In [26]:
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True) #batch_size will mean 64 examples are shown to the
                                                                      #nn per loop

### Class definition time!!

In [ ]:
class BCNet(nn.Module):
    
    def __init__(self):
        super(BCNet, self).__init__()
        
        self.fc1 = nn.Linear(30, 64)          #fc1 is the first "fully connected" layer, which recieves 30 inputs
                                              #and 
        self.fc2 = nn.Linear(64, 32)
        self.fc2 = nn.Linear(32, 1)
        
    def forward(self, x):
        